"""Package a harness directory into a portable, versioned artifact.

Produces ``<name>-<version_hash>.zip`` containing the harness folder plus a
``hiveloom.lock`` (runtime version, spec hash, creation date). With ``--docker``
it also emits a ``Dockerfile`` so the artifact becomes a runnable container.

Secrets and local run memory are never packaged: ``.env``, ``.hiveloom/``, and
``__pycache__`` are excluded (a deployment starts fresh; ``.env.example`` ships).
"""

from __future__ import annotations

import shutil
import zipfile
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

from hiveloom import __version__
from hiveloom.errors import SpecError
from hiveloom.logging.trace import spec_version_hash
from hiveloom.spec.loader import harness_path, load_spec, resolve_hooks

_DOCKERFILE = """\
# Auto-generated by `hiveloom package --docker`.
FROM python:3.11-slim
{runtime_install}
WORKDIR /harness
COPY . /harness
# Pass --input FILE|TEXT (and any flags) as container args:
#   docker run <image> --input notes.txt
ENTRYPOINT ["hiveloom", "run", ".", "--json"]
"""

_DOCKERIGNORE = """\
# Auto-generated by `hiveloom package --docker`.
# Never copy credentials or local run memory into a deployment image.
.env
.hiveloom/
__pycache__/
*.py[cod]
*.zip
.git/
"""

_EXCLUDE_DIRS = {"__pycache__", ".hiveloom", ".git"}
_EXCLUDE_NAMES = {".env"}


def _should_skip(rel: Path) -> bool:
    if any(part in _EXCLUDE_DIRS for part in rel.parts):
        return True
    if rel.name in _EXCLUDE_NAMES or rel.suffix in {".pyc", ".zip"}:
        return True
    return False


def _zip_dir(base: Path, zip_path: Path, top: str) -> list[str]:
    added: list[str] = []
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(base.rglob("*")):
            if not path.is_file():
                continue
            rel = path.relative_to(base)
            if _should_skip(rel):
                continue
            arcname = f"{top}/{rel.as_posix()}"
            archive.write(path, arcname)
            added.append(arcname)
    return added


def package_harness(
    harness_dir: str | Path,
    *,
    docker: bool = False,
    output_dir: str | Path | None = None,
    runtime_wheel: str | Path | None = None,
) -> dict[str, Any]:
    """Validate and package a harness. Returns a summary dict."""
    yaml_path = harness_path(harness_dir)
    base = yaml_path.parent
    if runtime_wheel is not None and not docker:
        raise SpecError("runtime_wheel requires docker=True")
    spec = load_spec(yaml_path)
    resolve_hooks(spec, base)  # never package an invalid harness
    version_hash = spec_version_hash(spec, base)

    from hiveloom import ext

    lock = {
        "name": spec.name,
        "runtime": f"hiveloom=={__version__}",
        "harness_hash": version_hash,
        "created_at": datetime.now(UTC).isoformat(),
    }
    packs = ext.packs_for_spec(spec)
    if packs:
        # Catalog entries this spec uses that come from extension packs — a
        # deployment must install these alongside the hiveloom runtime.
        lock["packs"] = packs
    (base / "hiveloom.lock").write_text(
        yaml.safe_dump(lock, sort_keys=False), encoding="utf-8"
    )

    dockerfile_written = False
    embedded_runtime: str | None = None
    if docker:
        runtime_install = f"RUN pip install --no-cache-dir hiveloom=={__version__}"
        if runtime_wheel is not None:
            wheel = Path(runtime_wheel).resolve()
            if not wheel.is_file() or wheel.suffix != ".whl":
                raise SpecError(
                    f"runtime wheel must be an existing .whl file (got {runtime_wheel})"
                )
            runtime_dir = base / "runtime"
            runtime_dir.mkdir(exist_ok=True)
            target = runtime_dir / wheel.name
            if wheel != target.resolve():
                shutil.copy2(wheel, target)
            embedded_runtime = f"runtime/{wheel.name}"
            runtime_install = (
                f"COPY {embedded_runtime} /tmp/{wheel.name}\n"
                f"RUN pip install --no-cache-dir /tmp/{wheel.name}"
            )
        (base / "Dockerfile").write_text(
            _DOCKERFILE.format(runtime_install=runtime_install), encoding="utf-8"
        )
        (base / ".dockerignore").write_text(_DOCKERIGNORE, encoding="utf-8")
        dockerfile_written = True

    out = Path(output_dir) if output_dir is not None else base.parent
    out.mkdir(parents=True, exist_ok=True)
    zip_path = out / f"{spec.name}-{version_hash}.zip"
    files = _zip_dir(base, zip_path, top=spec.name)

    return {
        "name": spec.name,
        "version_hash": version_hash,
        "zip_path": str(zip_path),
        "files": len(files),
        "dockerfile": dockerfile_written,
        "embedded_runtime": embedded_runtime,
    }
