"""Package a harness directory into a portable, versioned artifact.

Produces ``<name>-<version_hash>.zip`` containing the harness folder plus a
``hiveloom.lock`` (runtime version, spec hash, creation date). With ``--docker``
it also emits a ``Dockerfile`` so the artifact becomes a runnable container.

Secrets and local run memory are never packaged: ``.env*`` files, the configured
trace directory, and ``__pycache__`` are excluded (a deployment starts fresh;
``.env.example`` ships). ``is_sensitive_path`` is that exclusion predicate,
public and reused by the HTTP control plane's ``POST /run`` ``input_file``
handling — one definition of "never leaves the harness" for both.
"""

from __future__ import annotations

import shutil
import zipfile
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

from hiveloom import __version__
from hiveloom.errors import SpecError
from hiveloom.logging.trace import spec_version_hash
from hiveloom.spec.loader import atomic_write_text, harness_path, load_spec, resolve_hooks

_DOCKERFILE = """\
# Auto-generated by `hiveloom package --docker`.
FROM python:3.11-slim
{runtime_install}
WORKDIR /harness
COPY . /harness
# Pass --input FILE|TEXT (and any flags) as container args:
#   docker run <image> --input notes.txt
ENTRYPOINT ["hiveloom", "run", ".", "--json"]
"""

_DOCKERFILE_SERVE = """\
# Auto-generated by `hiveloom package --docker --serve`.
FROM python:3.11-slim
{runtime_install}
WORKDIR /harness
COPY . /harness
# Trust was granted by the human who ran `hiveloom package` (itself gated on
# trust); the image content is fixed from that point, so bake the decision in.
ENV HIVELOOM_TRUST=always
# Serve the harness over HTTP:
#   docker run -p 8080:8080 -e HIVELOOM_API_KEY=... <image>
# POST /runs {{"input": "...", "stream": true}} — GET /healthz for probes.
EXPOSE 8080
ENTRYPOINT ["hiveloom", "serve", ".", "--host", "0.0.0.0", "--port", "8080"]
"""

_DOCKERIGNORE = """\
# Auto-generated by `hiveloom package --docker`.
# Never copy credentials or local run memory into a deployment image.
.env*
!.env.example
!.env.template
.hiveloom/
__pycache__/
*.py[cod]
*.zip
.git/
"""

_EXCLUDE_DIRS = {"__pycache__", ".hiveloom", ".git"}
_ENV_TEMPLATES = {".env.example", ".env.template"}
_EXCLUDE_DIRS_CF = {name.casefold() for name in _EXCLUDE_DIRS}
_ENV_TEMPLATES_CF = {name.casefold() for name in _ENV_TEMPLATES}


def trace_dir_relative_to(base: Path, trace_dir: str) -> Path | None:
    """Return the configured trace directory when it lives inside ``base``."""
    configured = Path(trace_dir)
    resolved = configured.resolve() if configured.is_absolute() else (base / configured).resolve()
    try:
        return resolved.relative_to(base.resolve())
    except ValueError:
        # An external trace directory cannot be part of this package anyway.
        return None


def _cf_parts(path: Path) -> tuple[str, ...]:
    return tuple(part.casefold() for part in path.parts)


def is_sensitive_path(rel: Path, *, trace_dir: Path | None = None) -> bool:
    """The canonical "never leaves the harness" predicate for a path relative
    to a harness directory: local run/auth state (``.hiveloom/``, which holds
    the trust store, construction log, and — for a served harness —
    ``authorized_keys.json``), credentials (``.env*``, except the checked-in
    templates), VCS/cache noise, and the configured trace directory (which
    may live outside ``.hiveloom/`` if reconfigured).

    Every comparison is case-insensitive, unconditionally. ``.resolve()``
    does not correct a caller's casing to the on-disk name on a
    case-insensitive-but-case-preserving filesystem (macOS APFS, most
    Windows filesystems) — the OS still opens ``.HIVELOOM/...`` as
    ``.hiveloom/...`` while an exact-case comparison would wave it through.
    Under-blocking here leaks secrets; over-blocking a legitimately-named
    file that merely resembles ``.ENV`` is a trivially smaller cost.

    Public and reused verbatim by both ``package_harness`` (never zip these)
    and the HTTP control plane's ``POST /run``/tool-call path handling
    (never read or write these) — one definition, so packaging and serving
    can never disagree about what is sensitive.
    """
    rel_parts = _cf_parts(rel)
    if any(part in _EXCLUDE_DIRS_CF for part in rel_parts):
        return True
    if trace_dir is not None:
        trace_parts = _cf_parts(trace_dir)
        if rel_parts[: len(trace_parts)] == trace_parts:
            return True
    name_cf = rel.name.casefold()
    if (name_cf.startswith(".env") and name_cf not in _ENV_TEMPLATES_CF) or (
        rel.suffix.casefold() in {".pyc", ".zip"}
    ):
        return True
    return False


def _zip_dir(base: Path, zip_path: Path, top: str, *, trace_dir: Path | None) -> list[str]:
    added: list[str] = []
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(base.rglob("*")):
            if not path.is_file():
                continue
            rel = path.relative_to(base)
            if is_sensitive_path(rel, trace_dir=trace_dir):
                continue
            arcname = f"{top}/{rel.as_posix()}"
            archive.write(path, arcname)
            added.append(arcname)
    return added


def package_harness(
    harness_dir: str | Path,
    *,
    docker: bool = False,
    serve: bool = False,
    output_dir: str | Path | None = None,
    runtime_wheel: str | Path | None = None,
) -> dict[str, Any]:
    """Validate and package a harness. Returns a summary dict."""
    yaml_path = harness_path(harness_dir)
    base = yaml_path.parent
    if runtime_wheel is not None and not docker:
        raise SpecError("runtime_wheel requires docker=True")
    if serve and not docker:
        raise SpecError("serve requires docker=True")
    spec = load_spec(yaml_path)
    resolve_hooks(spec, base)  # never package an invalid harness
    version_hash = spec_version_hash(spec, base)
    trace_dir = trace_dir_relative_to(base, spec.logging.trace_dir)
    if trace_dir == Path("."):
        raise SpecError(
            "logging.trace_dir cannot be the harness root when packaging; "
            "use a subdirectory or an external trace directory"
        )

    from hiveloom import ext

    lock = {
        "name": spec.name,
        "runtime": f"hiveloom=={__version__}",
        "harness_hash": version_hash,
        "created_at": datetime.now(UTC).isoformat(),
    }
    packs = ext.packs_for_spec(spec)
    if packs:
        # Catalog entries this spec uses that come from extension packs — a
        # deployment must install these alongside the hiveloom runtime.
        lock["packs"] = packs
    atomic_write_text(base / "hiveloom.lock", yaml.safe_dump(lock, sort_keys=False))

    dockerfile_written = False
    embedded_runtime: str | None = None
    if docker:
        runtime_install = f"RUN pip install --no-cache-dir hiveloom=={__version__}"
        if runtime_wheel is not None:
            wheel = Path(runtime_wheel).resolve()
            if not wheel.is_file() or wheel.suffix != ".whl":
                raise SpecError(
                    f"runtime wheel must be an existing .whl file (got {runtime_wheel})"
                )
            runtime_dir = base / "runtime"
            runtime_dir.mkdir(exist_ok=True)
            target = runtime_dir / wheel.name
            if wheel != target.resolve():
                shutil.copy2(wheel, target)
            embedded_runtime = f"runtime/{wheel.name}"
            runtime_install = (
                f"COPY {embedded_runtime} /tmp/{wheel.name}\n"
                f"RUN pip install --no-cache-dir /tmp/{wheel.name}"
            )
        template = _DOCKERFILE_SERVE if serve else _DOCKERFILE
        atomic_write_text(base / "Dockerfile", template.format(runtime_install=runtime_install))
        dockerignore = _DOCKERIGNORE
        if trace_dir is not None and trace_dir.parts and trace_dir.parts[0] != ".hiveloom":
            dockerignore += f"{trace_dir.as_posix().rstrip('/')}/\n"
        atomic_write_text(base / ".dockerignore", dockerignore)
        dockerfile_written = True

    out = Path(output_dir) if output_dir is not None else base.parent
    out.mkdir(parents=True, exist_ok=True)
    zip_path = out / f"{spec.name}-{version_hash}.zip"
    files = _zip_dir(base, zip_path, top=spec.name, trace_dir=trace_dir)

    return {
        "name": spec.name,
        "version_hash": version_hash,
        "zip_path": str(zip_path),
        "files": len(files),
        "dockerfile": dockerfile_written,
        "serve": bool(docker and serve),
        "embedded_runtime": embedded_runtime,
    }
